-- ┌─────────────────────────────────────────────────────────────────┐
-- │ schema.sql intentionally left empty.                             │
-- │                                                                  │
-- │ The authoritative DB schema is the ordered set of migrations in  │
-- │ supabase/migrations/. Do NOT use this file for `supabase db      │
-- │ reset --schema` — it would skip every security-hardening         │
-- │ migration (0013–0021+) and reopen vulnerabilities (admin RLS,    │
-- │ rate guards, freeze triggers, GeoJSON validation, bidi checks).  │
-- │                                                                  │
-- │ To bootstrap a fresh DB, run migrations in order via:            │
-- │   supabase db push   (Supabase CLI)                              │
-- │ or apply files 0002_…sql … 0021_…sql sequentially in the SQL     │
-- │ Editor.                                                          │
-- │                                                                  │
-- │ If you need a snapshot, regenerate via:                          │
-- │   pg_dump --schema-only --no-owner --no-acl <db_url>             │
-- │ AFTER applying all migrations.                                   │
-- └─────────────────────────────────────────────────────────────────┘
